# k expose deployment hr-web-app --name=hr-web-app-service --type=NodePort --port=8080 -o yaml --dry-run=client
# k edit svc hr-web-app-service
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: hr-web-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}