apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hr-web-app
        image: kodekloud/webapp-color