apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-busybox
  name: static-busybox
spec:
  containers:
  - image: busybox
    name: static-busybox
    command: ["/bin/sh"]
    args: ["-c","sleep 1000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}