apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-resolver
  name: nginx-resolver
spec:
  containers:
  - image: nginx
    name: nginx-resolver
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {