apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: alpha
    env:
    - name: name
      value: alpha
    resources: {}
  - image: busybox
    name: beta
    command: ["/bin/sh"]
    args: ["-c", "sleep 4800"]
    env:
    - name: name
      value: beta
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}