apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dev-redis
  name: dev-redis
spec:
  containers:
  - image: redis:alpine
    name: dev-redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}