apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    environment: production
    tier: frontend
  name: hr-pod
  namespace: hr
spec:
  containers:
  - image: redis:alpine
    name: hr-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}