apiVersion: v1                                                                                                                                                                                             
kind: Pod 
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-via-file
  name: pod-secrets-via-file
spec:
  containers:
  - image: ngnix
    name: pod-secrets-via-file
    resources: {}
    volumeMounts:
    - name: foo 
      mountPath: /secrets
  volumes:
  - name: foo 
    secret:
      secretName: super-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
