apiVersion: v1
kind: Pod 
metadata:
  creationTimestamp: null
  labels:
    run: redis-storage
  name: redis-storage
spec:
  containers:
  - image: redis
    name: redis-storage
    volumeMounts:
    - mountPath: /data/redis
      name: cache-volume
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cache-volume
    emptyDir: {}                                                                                                                                                                                           
status: {}